### ISSUE TITLE
No module named pip

### ISSUE THREAD

**Issue by impiza** [kraanzu/gupshup#7]
python -m pip install git+https://github.com/kraanzu/gupshup.git change this to python3 -m pip install git+https://github.com/kraanzu/gupshup.git
![tt](https://user-images.githubusercontent.com/1174769/180179161-6b70b4f0-bbe4-4883-99cc-72840401d6bc.png)

**Comment by kraanzu** [comment]
Strange.... python seems to work just fine for me
Since both are same... I think i will change that
